### ISSUE TITLE
This relative module was not found:   * ./editorIcons.options in ./src/config/index.ts

### ISSUE THREAD

**Issue by bokeer** [heiyehk/electron-vue3-inote#1]
npm i 完成之后
npm run electron:serve 
报This relative module was not found:   * ./editorIcons.options in ./src/config/index.ts 错误
尝试 yarn install 也是一样

**Comment by heiyehk** [comment]
不好意思，没有看到，已修复。

**Comment by heiyehk** [comment]
= =，有点尴尬，本地没有更新了，直接在线上改的名字
