### ISSUE TITLE
数据能否存储在程序目录里

### ISSUE THREAD

**Issue by loveu5522** [heiyehk/electron-vue3-inote#11]
默认在C盘十分不安全，重装系统容易丢失。

**Comment by heiyehk** [comment]
> 默认在C盘十分不安全，重装系统容易丢失。

可以的，过几天我会重新发个版本，感谢体验使用。

**Comment by heiyehk** [comment]
[0..6.1](https://github.com/heiyehk/electron-vue3-inote/releases/tag/0.6.1)
