### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by a982246809** [heiyehk/electron-vue3-inote#3]
啥方法都试了  npm yarn

**Comment by heiyehk** [comment]
`electron`安装不了可以试试使用淘宝源或单独给`electron`设置源

[设置教程](https://github.com/heiyehk/electron-vue3-inote/wiki/electron%E5%AE%89%E8%A3%85%E5%8D%A1%E4%BD%8F%E3%80%81%E5%87%BA%E9%94%99%E3%80%81%E6%97%A0%E6%B3%95%E5%AE%89%E8%A3%85)
