### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by heiyehk** [heiyehk/electron-vue3-inote#6]
![](https://user-images.githubusercontent.com/63433257/143593043-d7ff94a3-53e0-4f83-905a-b1b48593367c.png)

我也遇到相同的问题，解决无果。求助！！！
node 版本  v16.13.0
npm  版本  v6.14.15

_Originally posted by @BuCai in https://github.com/heiyehk/electron-vue3-inote/issues/5#issuecomment-989675448_

**Comment by powerttt** [comment]
Mac 同样的问题。

**Comment by heiyehk** [comment]
> Mac 同样的问题。

好的，我尽快复原环境复现该问题fix。

**Comment by heiyehk** [comment]
目前猜测应该是vue的某个解析包的问题，目前正在重构，尽情期待。

**Comment by heiyehk** [comment]
> Mac 同样的问题。

修复了
