### ISSUE TITLE
在win10系统上，我的两台台式电脑上，安装0.31 不能正常工作

### ISSUE THREAD

**Issue by xingkong1983** [heiyehk/electron-vue3-inote#7]
![图片](https://user-images.githubusercontent.com/8519777/153758871-528fcbc7-be95-4b75-9d46-951b78175f80.png)

**Comment by heiyehk** [comment]
应该是以前版本的bug引起的，可以试试清一下缓存，替换User
`C:\Users\{User}\AppData\Roaming\i-notes`

**Comment by xingkong1983** [comment]
问题并没有解决，我在win11上，新系统使用2的版本是可以的，3的版本不行，使用管理员权限也不能使用。
安装顺序是先安装3，尝试各种管理员权限不行。
然后删除3，再安装2是正常的。

**Comment by heiyehk** [comment]
> 问题并没有解决，我在win11上，新系统使用2的版本是可以的，3的版本不行，使用管理员权限也不能使用。 安装顺序是先安装3，尝试各种管理员权限不行。 然后删除3，再安装2是正常的。

对不起，我有罪
![image](https://user-images.githubusercontent.com/33891067/174562055-3868dc9e-8bfb-4fef-93e1-91a2b512878b.png)
我没build  0.3.3的包
