### ISSUE TITLE
4加入了markdown 组件，但却没有那么精致了，还是喜欢版本3

### ISSUE THREAD

**Issue by xingkong1983** [heiyehk/electron-vue3-inote#9]
作者大大你好，4的版本不错，加入了markdown ， 但是这个 markdown 组件不太精致，相比较而言，我还是喜欢你做的版本3一些。
其实3如果加入图片缩略图9宫格，视频，附件等等，会很不错，我这边也做了一款类似的笔记软件，如果可以，咱们可以一起合作一个开源产品，我这边可以开源设计稿。

**Comment by heiyehk** [comment]
> 作者大大你好，4的版本不错，加入了markdown ， 但是这个 markdown 组件不太精致，相比较而言，我还是喜欢你做的版本3一些。 其实3如果加入图片缩略图9宫格，视频，附件等等，会很不错，我这边也做了一款类似的笔记软件，如果可以，咱们可以一起合作一个开源产品，我这边可以开源设计稿。

你好，感谢你的反馈。markdown的话我觉得是会一个比较不错文档编写方式，目前也还在观望其他的markdown组件。最近也会更新 `5` 的版本，附件、视频该类文件的话我觉得可能不会出现在便笺方面，当然也许有一天会支持。
目前精力可能不太支持去开发一个开源产品，不过以后还是可以多交流，也可以直接联系我的邮箱。
